name: Greeting on variable day

on:
  workflow_call:
    inputs:
      var3:
        type: string

env:
  DAY_OF_WEEK: Monday

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  job2:
    uses: ./.github/workflows/blank.yml
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job2.outputs.ip }}
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Printing from var file"
        run: echo "$var3"
        env:
          First_Name: Mona
