name: Greeting on variable day

on:
  workflow_call:
    inputs:
      var3:
        type: string

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Printing from var file"
        run: echo "$var3"
        env:
          First_Name: Mona
