name: Greeting on variable day

on:
  workflow_call:
    inputs:
      var3:
        type: string

env:
  DAY_OF_WEEK: Monday

jobs:
  job1:
    uses: github.com/molszowka/test/blob/main/.github/workflows/blank.yml@v1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.ip }}
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Printing from var file"
        run: echo "$var3"
        env:
          First_Name: Mona
